
name: release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
    
      - name: Create Release with softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the pushed tag name
          name: ${{ github.ref }}  # Optional: Set release name (defaults to tag_name)
          body: "**Release Notes:**  \n  * (Describe your changes here)"  # Optional release description
          files: 'release.zip'  # List your release assets here (replace with your pattern)
          draft: false 